setup.py

Commit 5f615bf introduced a dependency on certifi.
[cgoncalves@codfish ~]$ pytr help
Traceback (most recent call last):
File "/home/cgoncalves/.local/bin/pytr", line 5, in <module>
from pytr.main import main
File "/home/cgoncalves/.local/lib/python3.10/site-packages/pytr/main.py", line 14, in <module>
from pytr.account import login
File "/home/cgoncalves/.local/lib/python3.10/site-packages/pytr/account.py", line 9, in <module>
from pytr.api import TradeRepublicApi, CREDENTIALS_FILE
File "/home/cgoncalves/.local/lib/python3.10/site-packages/pytr/api.py", line 32, in <module>
import certifi
ModuleNotFoundError: No module named 'certifi'

Add certifi to requirement list

---

pytr/api.py
pytr/dl.py
pytr/portfolio.py
pytr/utils.py
setup.py

TradeRupublic made some changes in API.
Replace single command `portfolio` with multiple commands: `compactPortfolio`, `instrument` and `tick`.
As sidecar change show the name of the ISIN.
It also copy changes from https://github.com/marzzzello/pytr/pull/29.
Steps:
First merge: https://github.com/marzzzello/pytr/pull/29
Then need to rebase this changes.
closes: #37

Replace portfolio operation with compactPortfolio

---

pytr/main.py
pytr/portfolio.py

- add portfolio_to_csv method to Portfolio class
- extend argument parsing with path option for saving csv
- also add help string to -o option
- portfolio_to_csv executes after get() method when path for saving csv is provided
**Core idea:**
With this option, when providing the `-o` or `--output` option (and a filepath) to the portfolio command, the key information of the portfolio is exported to a csv file. This eases the use of net value and ISIN etc. for further analysis, since csv format is easier to use when needing further analysis than the formatted string output in the CLI.

Add option to save portfolio to csv

---

pytr/api.py

* allows to overwrite the path parameters for cookie and credential file in the constructor of TradeRepublicApi
* If they are not overwritten they default to the current parameters
Background: 
* I'm using the project as an api in a docker container and I want to change the hardcoded paths to point to another directory
* It was already possible to point to the key file, but not cookies or credentials

Add parameters for cookies and credential file to TradeRepublicApi constructor

---

pytr/api.py
pytr/dl.py
pytr/utils.py

Adds support for new Trade Republic API parts.
TR nows uses `timingTransaction` and `timelineActivityLog` instead of `timing` as well as `timingDetailV2` instead of `timingDetail`. 
As the new card transactions as well as saveback and round-up benefits are not included in the old API elements this change is required to include these. This pull-request fixes #53.
The naming of the output files and the format of the output JSON can be different from earlier versions.
The naming of the output files might be adapted further as they are now more information available in the  `timingDetailV2` data.

Timeline v2

---

pytr/utils.py

Adds two new types to `account_transcations.csv`: ATM withdraw (Barabhebung) and Card fee (Kartenausgabegebühr). 
To ease import to Portfolio Performance those are classified as 'removal' and a  new field ('note') with the actual removal reason is added.

Add note field to account_transcations.csv and add atm withdraw and card order type

---

pytr/utils.py

Currently, refunds on Visa credit card transactions are not included in the Portfolio Performance CSV.
`[
{
"id": "bc663404-36f7-5027-b0a6-ca9f856b7acb",
"timestamp": "2024-06-28T06:36:08.258+0000",
"title": "Amazon",
"icon": "logos/merchant-9c4e270f-84f4-4c45-9bfe-026d66d148b1/v2",
"badge": null,
"subtitle": null,
"amount": {
"currency": "EUR",
"value": 9.99,
"fractionDigits": 2
},
"subAmount": null,
"status": "EXECUTED",
"action": {
"type": "timelineDetail",
"payload": "bc663404-36f7-5027-b0a6-ca9f856b7acb"
},
"eventType": "card_refund",
"source": "timelineTransaction",
"details": {
"id": "bc663404-36f7-5027-b0a6-ca9f856b7acb",
"sections": [
{
"title": "Du hast 9,99 € erhalten",
"data": {
"icon": "logos/merchant-9c4e270f-84f4-4c45-9bfe-026d66d148b1/v2",
"subtitleText": null, …

Added missing handling of card refunds for portfolio performance csv export

---

pytr/account.py

This hides the PIN while it is entered using `getpass()`.
I have only tested this with a Linux terminal, Windows Powershell and Windows cmd.exe. It works there. I don't know what else people use to run this though.
An alternative could be https://github.com/asweigart/pwinput. That is also closer to the way the Trade Republic app hides the PIN but it requires using an extra package.

Hide PIN input

---

pytr/timeline.py

On my account, I get the message "Received duplicate event..." within an endless loop (all the time with the same 30 "duplicate events), so is it possible to set the variable added_last_event only, if there are no duplicates?

timeline: retrieve next timeline, only if in the response is at least one new entry

---

pytr/dl.py
pytr/event.py
pytr/event_formatter.py
pytr/locale/cs/LC_MESSAGES/messages.po
pytr/locale/da/LC_MESSAGES/messages.po
pytr/locale/de/LC_MESSAGES/messages.po
pytr/locale/en/LC_MESSAGES/messages.po
pytr/locale/es/LC_MESSAGES/messages.po
pytr/locale/fr/LC_MESSAGES/messages.po
pytr/locale/it/LC_MESSAGES/messages.po
pytr/locale/nl/LC_MESSAGES/messages.po
pytr/locale/pl/LC_MESSAGES/messages.po
pytr/locale/pt/LC_MESSAGES/messages.po
pytr/locale/ru/LC_MESSAGES/messages.po
pytr/locale/sk/LC_MESSAGES/messages.po
pytr/locale/zh/LC_MESSAGES/messages.po
pytr/main.py
pytr/timeline.py
pytr/transactions.py
pytr/translation.py

Refactors the parsing of all_events.json and the formatting into all_transactions.csv to capture all pp events generated by tr events, especially taxes, fees, and savebacks.
In detail:
~~1. Removes card_failed_transaction type due to it not being relevant for PP~~
2. Adds INCOMING_TRANSFER_DELEGATION and events from #116 (INTEREST_PAYOUT, card_successful_oct, TAX_REFUND, benefits_saveback_execution) to event.py
3. Introduces enums and dataclasses in event.py to a. structure and facilitate type matching b. differentiate between pp_types and types that require further csv formatting
4. Introduces tax and fee parsers in event.py
5. Introduces event_formatter.py to generate multiple csv lines from certain events (saveback, ~~taxed income, transactions with fees~~). Fees and taxes are added as …

Refactor parsing and formatting

---

pytr/event.py
pytr/event_formatter.py

Fix for #125 , where dictionary fields associated with "Aktien" are parsed with locale "en", and "Anteile", "Gebühr", "Steuer", "Steuern" are parsed with locale "de".
Also removes an unused import and handles a theoretical None case for event.value: Optional[float]

Fb parsing and formatting: locale aware parsing

---

pytr/event.py

see Issue: https://github.com/pytr-org/pytr/issues/127

fixed fees if not present

---

pytr/dl.py

Hi,
this should fix an issue that was initially reported in #109.
When downloading large numbers of timeline events, some subscriptions might yield errors. Such as shown in the logs:
`Received error message: '829 E {"errors":[{"errorCode":"UNKNOWN_ERROR","errorField":null,"errorMessage":"Could not process response","meta":{"source":"MAPPER"}}]}'`
I guess formerly it caused the downloading not to return at all. This endless waiting seems to have been fixed in 2f62b098e8e339f8bcfe65177adeb46a6b05efdd. However, this only makes pytr return at the cost of adding some double transactions in the resulting account_transactions.csv while leaving out the transactions where data retrieval from TR failed, because the loop in DL.dl_loop() is not broken up but rather feeded with the previous response. …

Re-subscribe in case of an error from Trade Republic

---

pytr/event.py

It can happen that deposits get canceled. E.g. when you send money from another person's bank account which Trade Republic will reject. In that case, the deposit is canceled and no effective transaction should be created.

Ignore canceled deposits

---

pyproject.toml

Addresses https://github.com/pytr-org/pytr/issues/143 until someone comes along and updates the code to be compatible with websockets 14.x

Pin `websockets<14`

---

pyproject.toml

The url to the homepage on PyPI points to a repository on Gitlab which apparently does not exist.

Set correct project url

---

pytr/dl.py
pytr/timeline.py

The Christmas Gift event was causing errors, see
* https://github.com/pytr-org/pytr/issues/148
* https://github.com/pytr-org/pytr/issues/151
There might be a sensible way to handle this event, but before that I think it makes sense to make it so the `dl_docs` command doesn't outright crash when there's an unsupported event in the timeline.
Inspired largely by @zonefuenf (https://github.com/pytr-org/pytr/issues/148#issuecomment-2532089877)

Ignore unsupported Timeline events and log them

---

pytr/dl.py
pytr/timeline.py

Thanks to **@NiklasRosenstein** and **@zonefuenf** for their work on [#161](https://github.com/pytr-org/pytr/pull/161), which introduced support for `UnsupportedEventError` to handle Trade Republic’s Christmas Gift event. While this resolved the initial issue, a new problem emerged: when an `UnsupportedEventError` occurs, the `received_detail` counter does not increment. This prevents the termination condition `received_detail == requested_detail` from ever being met, causing the `dl_docs` script to hang and PDFs to not be stored in the folder. Consequently, the issue with the script not finishing and thus not outputting any of the PDF files still persists.
**What This PR Does**  
- **Introduces a `skipped_detail` counter** to track events that trigger `UnsupportedEventError`.  
- …

Fix: Handle skipped timeline details properly to avoid script getting stuck with UnsupportedEventError

---

.github/workflows/publish-pypi.yml
pyproject.toml

This PR makes it so Pytest is run before the `build-n-publish` CI job.

Run Pytest in CI

---

.github/workflows/publish-pypi.yml
README.md
pyproject.toml
pytr/account.py
pytr/alarms.py
pytr/api.py
pytr/details.py
pytr/dl.py
pytr/event.py
pytr/event_formatter.py
pytr/main.py
pytr/portfolio.py
pytr/timeline.py
pytr/translation.py
pytr/utils.py
tests/test_event.py
tests/test_event_csv_formatter.py

This PR adds [Ruff] as a development dependency and uses it in CI to check for lints and to enforce formatting.
[Ruff]: https://astral.sh/ruff

Add Ruff formatting & linting

---

.github/workflows/publish-pypi.yml
pytr/timeline.py

Update the `on` configuration of the workflow:
- Trigger on pushes to the main branch (`master`)
- Trigger on any pull requests
- Remove `workflow_dispatch` trigger (it appears to be unused)

Run CI on Pull Requests

---

.github/workflows/publish-pypi.yml

This is necessary because unfortunately the version that was pinned did not support Python package metadata version 2.4, which is the version that `uv build` with Hatchling produced.
```
Metadata-Version: 2.4
Name: pytr
Version: 0.4.0
Summary: Use TradeRepublic in terminal
...
```
This made the release job for 0.4.0 fail, unfortunately.

Upgrade PyPI publish version from v1.9 to v1 (i.e. using the latest in the major version 1)

---

pytr/event_formatter.py
pytr/main.py
pytr/transactions.py

With the new `pytr export_transactions --date-isoformat` option, the date column is formatted in ISO-8601 including the timestamp.
```csv
Date;Type;Value;Note;ISIN;Shares;Fees;Taxes
2025-02-01T06:55:39;Interest;24.52;Zinsen;;;;-878
2024-12-01T16:09:19;Interest;6.53;Zinsen;;;;
```
Closes #165

Add a `--date-isoformat` option to `pytr export_transactions`

---

pytr/event.py
tests/sample_credit_card_deposit.json
tests/test_event_csv_formatter.py

We missed mapping the `PAYMENT_INBOUND_CREDIT_CARD` transaction type, and deposits via credit card or Google Pay, etc. can have fees attached to them that we did not parse.

Map `PAYMENT_INBOUND_CREDIT_CARD` transaction and parse fees for deposits/removals

---

.gitignore

This file gets created on my Windows. Should be ignored for git.

Ignore uv.lock

---

pytr/event.py

The TR API now seems to return a new section in its dictionary for card transactions which has no element named "title". The current code, however, expects this key. This fix will make the code tolerant to this. The PR should fix #200.
Also add another known ignored event: `RDD_FLOW`

Accept sections without titles

---

pytr/dl.py
pytr/event.py
pytr/main.py
pytr/timeline.py

Due to recent changes in responses from the TR API, documents sections of TR data might not contain "detail" entries any more. These were used to get document timestamps from.
With this change we don't use the "detail" field any more for timestamps but solely rely on the event timestamp. Should anyone see issues with that, e.g. wrong document timestamps, please report this and we might consider looking for "detail" in certain cases.
This change also cleans up the subfolder structure for downloaded documents and tries to improve document naming. Please also report issues/regressions.
Should fix #206

Fix dl_docs command

---

.github/workflows/publish-pypi.yml

This fixes the python version selection for the CI tests.

ci: fix python version

---

pytr/event.py
tests/sample_sell_dividend.json
tests/test_event.py

On (knockout-)options, before this it would assign the ISIN of the underlying instrument instead of the ISIN of the option itself and the amount of options was also missing.
If you want I can also craft a testcase for this.

Fix dividends on knock-outs

---

pyproject.toml
pytr/main.py
pytr/portfolio.py

This change adds some features to portfolio export.
It is now possible to optionally include watchlist positions. If included, they will have a quantity of 0 obviously.
A price column was added to the output.
It is now possible to sort the output by a certain column. Default sorting is by market value, descending (as you see it in the Trade Republic app).
When you epxort the data to a csv file, only the overview is shown in console output.

Improve portfolio listing: optional inclusion of watchlist, more sorting and output options
